assemblyai:
  api_key: "YOUR_ASSEMBLYAI_API_KEY"

llm:
  endpoint: "https://api.openai.com/v1"
  model_name: "gpt-4"
  small_model_name: "gpt-4o-mini"
  api_key: "YOUR_LLM_API_KEY"

smtp:
  server: "smtp.gmail.com"
  port: 587
  ssl: true
  username: "YOUR_SMTP_USERNAME"
  password: "YOUR_SMTP_PASSWORD"
  sender_email: "your_email@example.com"
  destination_email: "destination@example.com"

fetchtranscript:
  api_key: "YOUR_FETCHTRANSCRIPT_API_KEY"

data:
  directory: "./data"
  sqlite_path: "./db.sqlite"

feed_categories:
  youtube_category:
    - "Youtube"
  podcast_category:
    - "Podcasts"

ignored_feeds: []
  # - "Feed Name To Ignore"
